### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by omilun** [FG42/FG42#16]
i have some error when i put `make install` on terminal:

**Creating the link...
rm: cannot remove '/usr/local/bin/fg42': No such file or directory
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1**

i used to root user when i install FG42 and i am sure about permissions.

**Comment by omilun** [comment]
I installed it.
I create a file name fg42 on the path `/usr/local/bin/` before `make install` command . 
my os is Fedora 25 .

**Comment by lxsameer** [comment]
Thanks for reporting. You should not install `FG42` using root. Also I fixed the problem

**Comment by omilun** [comment]
yes you are right. i used root user when it sad me that Error . i thought it dose not have some permissions .
