### ISSUE TITLE
Dired+- is missing in MELPA

### ISSUE THREAD

**Issue by littlebzh** [FG42/FG42#17]
At first launch of fg42 after fresh install

\*Messages\*

Initializing FPKG
Loading /home/plop/.fg42.el (source)...done
’dired+’ package is not installed
Refreshing package database...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:80 [2 times]
Contacting host: melpa.org:80
Package refresh done
package-compute-transaction: Package ‘dired+-’ is unavailable

I tried to find a reason for this.
https://emacs.stackexchange.com/questions/38553/dired-missing-from-melpa/38555

So, it's seems to be definitive (and probably for other emacswiki packages)
https://emacs.stackexchange.com/questions/38553/dired-missing-from-melpa/38555

**Comment by lxsameer** [comment]
Thanks for reporting. Moved the `dired+` to an ability which is disabled by default. As you mentioned it's not on Melpa any more. I have to review all the emacswiki packages and provide a solution for installing them.
